### ISSUE TITLE
The screenshot link(s) is(are) broken

### ISSUE THREAD

**Issue by duianto** [aaronbieber/tiny-menu.el#7]
When the screenshot link (right click, copy image address (google chrome)):
https://camo.githubusercontent.com/247cb7707c2dd5fb7b09cfabed6bf5200c71be58/687474703a2f2f6161726f6e6269656265722e636f6d2f6173736574732f696d616765732f74696e792d6d656e752d73637265656e73686f742e706e67

Is opened directly, then an almost blank page is shown, with just the text:
>Not Found

And the screenshot link in the README.md file is:
http://aaronbieber.com/assets/images/tiny-menu-screenshot.png

It leads to a 404 Not Found page with the text:
>404 Not Found

>nginx/1.4.6 (Ubuntu)

**Comment by aaronbieber** [comment]
I moved the asset into the repo and changed the Markdown to link to the raw asset on Github's CDN.
